### ISSUE TITLE
Link shinyapps.io

### ISSUE THREAD

**Issue by aephidayatuloh** [farhannarendraa/projectgacha#1]
Boleh ditambahkan link shinyapps.io dari aplikasi ini agar saya bisa akses secara online?

Terima kasih dan salam,
Aep

**Comment by farhannarendraa** [comment]
Baik pak, berikut link shinyapps di bawah ini:
http://widyaluth.shinyapps.io/gacha-simulator101/

**Comment by aephidayatuloh** [comment]
Terima kasih
